name: realm
version: 0.0.1
description: Realm experimental wrapper. Demo for dart:ffi preview.
author: Nabil Hachicha <nabil.hachicha@gmail.com>
environment:
  sdk: '>=2.5.0-dev.1.0 <3.0.0'
dev_dependencies:
  test: ^1.5.3
  pedantic: ^1.8.0